title: Pyllia Docs
description: Lightweight Python terminal
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

nav:
  - Home: index.md
  - Install: pages/install.md
  - Commands: pages/commands.md
